version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    networks:
        - backend
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 2s
      retries: 5


networks:
  backend:
    driver: bridge
