version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    networks:
        - backend
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 2s
      retries: 5
  auth_database:
    image: postgres:15
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB -p $POSTGRES_PORT" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  backend:
    driver: bridge
