version: '3.9'

services:
  rabbitmq:
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
  auth_database:
    ports:
      - "${POSTGRES_PORT_AUTH}:5432"
    volumes:
      - auth_db_dev:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST: "${POSTGRES_HOST_AUTH}"
      POSTGRES_PORT: "${POSTGRES_PORT_AUTH}"
      POSTGRES_DB: "${POSTGRES_DB_AUTH}"
      POSTGRES_USER: "${POSTGRES_USER_AUTH}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD_AUTH}"
    env_file:
      - .env
  tasks_database:
    ports:
      - "${POSTGRES_PORT_TASKS}:5432"
    volumes:
      - tasks_db_dev:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST: "${POSTGRES_HOST_TASKS}"
      POSTGRES_PORT: "${POSTGRES_PORT_TASKS}"
      POSTGRES_DB: "${POSTGRES_DB_TASKS}"
      POSTGRES_USER: "${POSTGRES_USER_TASKS}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD_TASKS}"
    env_file:
      - .env
  accounting_database:
    ports:
      - "${POSTGRES_PORT_ACCOUNTING}:5432"
    volumes:
      - accounting_db_dev:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST: "${POSTGRES_HOST_ACCOUNTING}"
      POSTGRES_PORT: "${POSTGRES_PORT_ACCOUNTING}"
      POSTGRES_DB: "${POSTGRES_DB_ACCOUNTING}"
      POSTGRES_USER: "${POSTGRES_USER_ACCOUNTING}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD_ACCOUNTING}"
    env_file:
      - .env
  redis:
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_dev:/data

volumes:
  tasks_db_dev:
  auth_db_dev:
  redis_dev:
  accounting_db_dev:
