"""tasks

Revision ID: 5d82a8e92211
Revises: a21a2be0eff5
Create Date: 2024-03-04 01:21:28.893017

"""
# stdlib
from typing import Sequence, Union

# thirdparty
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5d82a8e92211"
down_revision: Union[str, None] = "a21a2be0eff5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="ID",
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("OPEN", "CLOSED", name="task_status"),
            nullable=False,
        ),
        sa.Column("assigned_to", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Creation date",
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Modified date",
        ),
        sa.ForeignKeyConstraint(
            ["assigned_to"],
            ["user.email"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task")
    op.execute("DROP TYPE task_status")

    # ### end Alembic commands ###
