"""value_transaction

Revision ID: 24383b165bf8
Revises: c416fe69702f
Create Date: 2024-03-10 22:30:17.283440

"""
# stdlib
from typing import Sequence, Union

# thirdparty
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "24383b165bf8"
down_revision: Union[str, None] = "c416fe69702f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transaction",
        sa.Column(
            "value",
            sa.Integer(),
            nullable=True,
            comment="Transaction value with sign",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transaction", "value")
    # ### end Alembic commands ###
