"""initial

Revision ID: 46e465141c60
Revises:
Create Date: 2024-03-10 19:54:04.100609

"""
# stdlib
from typing import Sequence, Union

# thirdparty
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "46e465141c60"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column(
            "email", sa.String(), nullable=False, comment="Email of user"
        ),
        sa.Column(
            "first_name",
            sa.String(),
            nullable=True,
            comment="First Name of user",
        ),
        sa.Column(
            "last_name",
            sa.String(),
            nullable=True,
            comment="Last Name of user",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            comment="Is this user active or not",
        ),
        sa.Column(
            "role",
            sa.Enum("PARROT", "MANAGER", "ACCOUNTANT", name="role"),
            nullable=False,
            comment="User Role",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Creation date",
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Modified date",
        ),
        sa.PrimaryKeyConstraint("email"),
    )
    op.create_table(
        "task",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="ID",
        ),
        sa.Column(
            "closing_price",
            sa.Float(),
            server_default=sa.text("floor(random() * 20 + 20)::int;"),
            nullable=True,
            comment="Price of closing of this task",
        ),
        sa.Column(
            "assigning_price",
            sa.Float(),
            server_default=sa.text("floor(random() * 10 + 10)::int;"),
            nullable=True,
            comment="Price of closing of this task",
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("assigned_to", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Creation date",
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Modified date",
        ),
        sa.ForeignKeyConstraint(
            ["assigned_to"],
            ["user.email"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task")
    op.drop_table("user")
    # ### end Alembic commands ###
