"""accounting_specific_tables

Revision ID: 875b7c39e987
Revises: 46e465141c60
Create Date: 2024-03-10 21:02:08.131863

"""
# stdlib
from typing import Sequence, Union

# thirdparty
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "875b7c39e987"
down_revision: Union[str, None] = "46e465141c60"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "billing_cycle",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="ID",
        ),
        sa.Column("user", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("open", "paid", name="billingcyclestatus"),
            nullable=False,
            comment="Billing Cycle",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Creation date",
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Modified date",
        ),
        sa.ForeignKeyConstraint(
            ["user"],
            ["user.email"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "transaction",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="ID",
        ),
        sa.Column("billing_cycle_id", sa.UUID(), nullable=True),
        sa.Column(
            "description",
            sa.String(),
            nullable=True,
            comment="Description of transaction",
        ),
        sa.Column("task_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Creation date",
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Modified date",
        ),
        sa.ForeignKeyConstraint(
            ["billing_cycle_id"],
            ["billing_cycle.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["task.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transaction")
    op.drop_table("billing_cycle")
    # ### end Alembic commands ###
