"""task_public_id

Revision ID: c416fe69702f
Revises: 875b7c39e987
Create Date: 2024-03-10 21:36:09.831214

"""
# stdlib
from typing import Sequence, Union

# thirdparty
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c416fe69702f"
down_revision: Union[str, None] = "875b7c39e987"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task",
        sa.Column("public_id", sa.UUID(), nullable=True, comment="public ID"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task", "public_id")
    # ### end Alembic commands ###
