"""user

Revision ID: ee4e3f6cc867
Revises:
Create Date: 2024-03-03 20:05:18.187564

"""
# stdlib
from typing import Sequence, Union

# thirdparty
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ee4e3f6cc867"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column(
            "email", sa.String(), nullable=False, comment="Email of user"
        ),
        sa.Column(
            "first_name",
            sa.String(),
            nullable=True,
            comment="First Name of user",
        ),
        sa.Column(
            "last_name",
            sa.String(),
            nullable=True,
            comment="Last Name of user",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            comment="Is this user active or not",
        ),
        sa.Column(
            "password",
            sqlalchemy_utils.types.password.PasswordType(length=1137),
            nullable=False,
        ),
        sa.Column(
            "role",
            sa.Enum("MANAGER", name="role"),
            nullable=False,
            comment="User Role",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Creation date",
        ),
        sa.Column(
            "modified_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Modified date",
        ),
        sa.PrimaryKeyConstraint("email"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    # ### end Alembic commands ###
